name: FTP Deploy

on:
  push:
  workflow_dispatch:

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Sync file
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.ae-isae-supaero.fr
          username: ${{ secrets.corodro_ftp_username }}
          password: ${{ secrets.corodro_ftp_password }}
          port: 21
          protocol: ftp
          security: loose
          exclude: .git*
            - .git*/**
            - README.md
            - LICENSE
            - .vscode
            - .github*
            - .github*/**
